default:
  package_configs: &default_package_configs
    archs:
      - x86_64
    gcc_versions: 
      - '10'
    apple_clang_versions: 
      - '11'
      - '12'
    cppstds: 
      - 20
    upload_dependencies: all
  common_build_configs: &default_common_build_configs
    pure_c: false
    shared_option_name: false
    header_only: false

packages:
  - package_configs:
      <<: *default_package_configs
      conanfile: flatbuffersPkg/all/conanfile.py
      reference: flatbuffers/2.0.0@
    common_build_configs:
      <<: *default_common_build_configs
      build_all_options_values: 
        - flatbuffers:options_from_context

  - package_configs:
      <<: *default_package_configs
      conanfile: LLVM_corePkg/all/conanfile.py
      reference: llvm-core/12.0.0@
    common_build_configs: 
      <<: *default_common_build_configs

  - package_configs:
      <<: *default_package_configs
      conanfile: ClangPkg/all/conanfile.py
      reference: Clang/12.0.0@
    common_build_configs: 
      <<: *default_common_build_configs  

  - package_configs:
      <<: *default_package_configs
      conanfile: HalidePkg/all/conanfile.py
      reference: Halide/12.0.0@
    common_build_configs: 
      <<: *default_common_build_configs